def sniffbanner():
    print("")
    print("                          o   ")
    print("                   o       /      ")
    print("                    \     /       ")
    print("                     \   /        ")
    print("                      \ /         ")
    print("                 ______________       ")
    print("                |.------------.|          ")
    print("                ||            ||          ")
    print("                ||   TRAFIC   ||          ")
    print("                ||            ||          ")
    print("                ||            ||          ")
    print("                ||____________||_         ")
    print("                |OO ....... OO | `-.          ")
    print("                '------_.-._---' _.'          ")
    print("                 _____||   ||___/_            ")
    print("                /  _.-|| N ||-._  \      .-._             ")
    print("               / -'_.---------._'- \    ,'___i--i___      ")
    print("              /_.-'_  SNIFFER  _'-._\  ' /_+  o :::_\         ")
    print("             |`-i /m\/m\|\|/=,/m\i-'|  | || \ O /  ||          ")
    print("             |  |_\_/\_/___\_/'./|  |  | \/  \ /   \/              ")
    print("              `-'              '-.`-'  ,                          ")
    print("")
if __name__ == "__main__":
    sniffbanner()