def info_banner():
    print("                                                                     ")
    print("                                    /T /I                            ")
    print("                                    / |/ | .-~/                      ")
    print("                                T\ Y  I  |/  /  _                    ")
    print("                /T               | \I  |  I  Y.-~/                   ")
    print("                I l   /I       T\ |  |  l  |  T  /                   ")
    print("        __  | \l   \l  \I l __l  l   \   `  _. |                     ")
    print("        \ ~-l  `\   `\  \  \\ ~\  \   `. .-~   |                     ")
    print("        \   ~-. '-.  `  \  ^._ ^. '-.  /  \   |                      ")
    print("      .--~-._  ~-  `  _  ~-_.-'-.' ._ /._ .' ./                    ")
    print("        >--.  ~-.   ._  ~>-'    '\\   7   7   ]                      ")
    print("       ^.___~'--._    ~-{  .-~ .  `\ Y . /    |                     ")
    print("        <__ ~'-.  ~       /_/   \   \I  Y   : |                      ")
    print("        <__ ~'-.  ~       /_/   \   \I  Y   : |                      ")
    print("        ^-.__           ~(_/   \   >._:   | l______                  ")
    print("            ^--.,___.-~'  /_/   !  `-.~'--l_ /     ~'-.              ")
    print("                    (_/ .  ~(   /'     '~'--,Y   -=b-. _)            ")
    print("                    (_/ .  \  :           / l      c'~o \            ")
    print("                        \ /    `.    .     .^   \_.-~'~--.)         ")
    print("                        (_/ .   `  /     /       !       )/          ")
    print("                        / / _.   '.   .':      /        '            ")
    print("                        ~(_/ .   /    _  `  .-<_      -Information is more Important than you Think !!!")
    print("                            /_/ . ' .-~' `.  / \  \          ,z=.    ")
    print("                            ~( /   '  :   | K   '-.~-.______//       ")
    print("                              '-,.    l   I/ \_    __{--->._(==.       ")
    print("                            //(     \  <    ~'~'     //              ")
    print("                            /' /\     \  \     ,v=.  ((              ")
    print("                            .^. / /\     '  }__ //===-  `            ")
    print("                        / / ' '  '-.,__ {---(==-                     ")
    print("                        .^ '       :  T  ~'   ll                     ")
    print("                        / .  .  . : | :!        \\                   ")
    print("                     (_/  /   | | j-'          ~^                     ")
    print("                     (_/  /   | | j-'          ~^                     ")  
    print("                          ~-<_(_.^-~'                                  ")
    print("                                                                     ")
if __name__ == "__main__":
    info_banner()