def socialbanner():
    print("")
    print("     ,   A           {}                       ")
    print("    / \, | ,        .--.                     ")
    print("       =|= >       /.--.\                    ")
    print("    \ /` | `       |====|                    ")
    print("     `   |         |`::`|                    ")
    print("         |     .-;`\..../`;_.-^-._           ")
    print("         /\\/  /  |...::..|`   :   `|        ")
    print("         /\\/  /  |...::..|`   :   `|        ")
    print("        |:'\ |   /'''::''|   .:.   |        ")
    print("         \ /\;-,/\   ::  |..:::::..|        ")
    print("         |\ <` >  >._::_.| ':::::' |        ")
    print("         | `**`  /   ^^  |   ':'   |        ")
    print("         |       |       \    :    /        ")
    print("         |       |        \   :   /         ")
    print("         |       |___/\___|`-.:.-`          ")
    print("         |        \_ || _/    `       -Social      ")
    print("         |        <_ >< _>                 Engineering ")
    print("         |        |  ||  |                  ")
    print("         |        |  ||  |                  ")
    print("         |       _\.:||:./_                 ")
    print("         |      /____/\____\                ")
    print("")
if __name__ == "__main__":
    socialbanner()